# Generated by Django 4.2.3 on 2023-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("phone_number", models.CharField(max_length=25, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Otpcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                ("code", models.PositiveSmallIntegerField()),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codeID", models.CharField(max_length=11)),
                ("firstname", models.CharField(max_length=11)),
                ("lastname", models.CharField(max_length=11)),
                (
                    "typebime",
                    models.CharField(
                        choices=[
                            ("تامین اجتماهی ", "تامین اجتماهی"),
                            ("فرهنگی ", "فرهنگی"),
                            ("ازاد ", "گزینه 3"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "infopatent",
                    models.CharField(
                        choices=[("عکس ", "گزینه 1"), ("ازمایش  ", "گزینه 2")],
                        max_length=20,
                    ),
                ),
                ("typeSickness", models.CharField(max_length=11)),
                ("age", models.CharField(max_length=10)),
                ("textSickness", models.TextField()),
            ],
        ),
    ]
