# Generated by Django 4.2.3 on 2023-07-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("turn", "0002_appointment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="user",
        ),
    ]
